<?php declare(strict_types=1);

namespace DreiscSeoPro\Core\Content\Category;

use DreiscSeoPro\Core\Content\Product\ProductEnum;

class CategoryEnum
{
    final public const CUSTOM_FIELD__DREISC_SEO_RICH_SNIPPET__ITEM_CONDITION = ProductEnum::CUSTOM_FIELD__DREISC_SEO_RICH_SNIPPET__ITEM_CONDITION;
    final public const CUSTOM_FIELD__DREISC_SEO_RICH_SNIPPET__AVAILABILITY = ProductEnum::CUSTOM_FIELD__DREISC_SEO_RICH_SNIPPET__AVAILABILITY;
    final public const CUSTOM_FIELD__DREISC_SEO_RICH_SNIPPET__CUSTOM_SKU = ProductEnum::CUSTOM_FIELD__DREISC_SEO_RICH_SNIPPET__CUSTOM_SKU;
    final public const CUSTOM_FIELD__DREISC_SEO_RICH_SNIPPET__CUSTOM_MPN = ProductEnum::CUSTOM_FIELD__DREISC_SEO_RICH_SNIPPET__CUSTOM_MPN;
    final public const CUSTOM_FIELD__DREISC_SEO_RICH_SNIPPET__PRICE_VALID_UNTIL_DATE = ProductEnum::CUSTOM_FIELD__DREISC_SEO_RICH_SNIPPET__PRICE_VALID_UNTIL_DATE;

    final public const CUSTOM_FIELD__DREISC_SEO_ROBOTS_TAG = ProductEnum::CUSTOM_FIELD__DREISC_SEO_ROBOTS_TAG;

    final public const CUSTOM_FIELD__DREISC_SEO_FACEBOOK_TITLE = ProductEnum::CUSTOM_FIELD__DREISC_SEO_FACEBOOK_TITLE;
    final public const CUSTOM_FIELD__DREISC_SEO_FACEBOOK_DESCRIPTION = ProductEnum::CUSTOM_FIELD__DREISC_SEO_FACEBOOK_DESCRIPTION;
    final public const CUSTOM_FIELD__DREISC_SEO_FACEBOOK_IMAGE = ProductEnum::CUSTOM_FIELD__DREISC_SEO_FACEBOOK_IMAGE;
    final public const CUSTOM_FIELD__DREISC_SEO_TWITTER_TITLE = ProductEnum::CUSTOM_FIELD__DREISC_SEO_TWITTER_TITLE;
    final public const CUSTOM_FIELD__DREISC_SEO_TWITTER_DESCRIPTION = ProductEnum::CUSTOM_FIELD__DREISC_SEO_TWITTER_DESCRIPTION;
    final public const CUSTOM_FIELD__DREISC_SEO_TWITTER_IMAGE = ProductEnum::CUSTOM_FIELD__DREISC_SEO_TWITTER_IMAGE;

    final public const CUSTOM_FIELD__DREISC_SEO_CANONICAL_LINK_TYPE = ProductEnum::CUSTOM_FIELD__DREISC_SEO_CANONICAL_LINK_TYPE;
    final public const CUSTOM_FIELD__DREISC_SEO_CANONICAL_LINK_REFERENCE = ProductEnum::CUSTOM_FIELD__DREISC_SEO_CANONICAL_LINK_REFERENCE;
}
