<?php declare(strict_types=1);

namespace DreiscSeoPro\Migration;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Migration\MigrationStep;

class Migration9000000010AddAiExampleTemplates extends MigrationStep
{
    public function getCreationTimestamp(): int
    {
        return (int) 9_000_000_010;
    }

    public function update(Connection $connection): void
    {
        try {
            $connection->executeStatement("
                INSERT INTO `dreisc_seo_bulk_template` (`id`, `area`, `seo_option`, `name`, `spaceless`, `ai_prompt`, `template`, `created_at`, `updated_at`) VALUES
                (UNHEX('019271A055B975D38C839E20F079A78C'),	'product',	'metaTitle',	'dreiscSeoBulkProduct.defaultTemplates.metaTitle.openAiExampleEnglish',	0,	1,	'Create a search engine suitable SEO title for the product with the name: \n\'{{ product.translated.name }}\'\n{% if product.manufacturer.translated is defined %}\nfrom the manufacturer \'{{ product.manufacturer.translated.name }}\'\n{% endif %}\n\n{# Add the variant options, if it is a variant #}\n{% if isVariant and product.options is defined %}\n    The product is a variant with the following characteristics:\n    {% set optionStrings = [] %}\n	{% for option in product.options %}\n	    {% set singleOption = [option.group.translated.name, option.translated.name]|join(\'=\') %}\n	    {% set optionStrings = optionStrings|merge([singleOption]) %}\n	{% endfor %}\n	\n    {{ optionStrings|join(\' and \') }}\n{% endif %}\n\nThe text should be approximately 70 characters long.\nIt is important that the output is entirely in german.\nDo not put the result in quotation marks.\n\nThe following description text of the product serves as the basis for the SEO title:\n{{ product.translated.description }}',	'2024-10-09 14:23:06.251',	'2024-10-09 14:26:13.300'),
                (UNHEX('019271ABED73701E87B650FEAD42B60D'),	'product',	'metaTitle',	'dreiscSeoBulkProduct.defaultTemplates.metaTitle.openAiExampleGerman',	0,	1,	'Erstellen Sie einen für Suchmaschinen geeigneten SEO-Titel für das Produkt mit dem Namen: \n\'{{ product.translated.name }}\'\n{% if product.manufacturer.translated is defined %}\nvon dem Hersteller mit dem Namen: \'{{ product.manufacturer.translated.name }}\'\n{% endif %}\n\n{# Add the variant options, if it is a variant #}\n{% if isVariant and product.options is defined %}\n    Bei dem Produkt handelt es sich um eine Variante mit folgenden Eigenschaften:\n    {% set optionStrings = [] %}\n	{% for option in product.options %}\n	    {% set singleOption = [option.group.translated.name, option.translated.name]|join(\'=\') %}\n	    {% set optionStrings = optionStrings|merge([singleOption]) %}\n	{% endfor %}\n	\n    {{ optionStrings|join(\' und \') }}\n{% endif %}\n\nDer Text sollte ca. 70 Zeichen lang sein.\nWichtig ist, dass die Ausgabe komplett in Deutsch erfolgt.\nSetzen Sie das Ergebnis nicht in Anführungszeichen.\n\nAls Grundlage für den SEO-Titel dient folgender Beschreibungstext des Produktes:\n{{ product.translated.description }}',	'2024-10-09 14:25:59.636',	'2024-10-09 14:30:19.058'),
                (UNHEX('019271B5D2CF758DA5B62CC4A5441C92'),	'product',	'metaDescription',	'dreiscSeoBulkProduct.defaultTemplates.metaDescription.openAiExampleGerman',	1,	1,	'Erstellen Sie eine für Suchmaschinen geeigneten SEO-Beschreibung für das Produkt mit dem Namen: \n\'{{ product.translated.name }}\'\n{% if product.manufacturer.translated is defined %}\nvon dem Hersteller mit dem Namen: \'{{ product.manufacturer.translated.name }}\'\n{% endif %}\n\n{# Add the variant options, if it is a variant #}\n{% if isVariant and product.options is defined %}\n    Bei dem Produkt handelt es sich um eine Variante mit folgenden Eigenschaften:\n    {% set optionStrings = [] %}\n	{% for option in product.options %}\n	    {% set singleOption = [option.group.translated.name, option.translated.name]|join(\'=\') %}\n	    {% set optionStrings = optionStrings|merge([singleOption]) %}\n	{% endfor %}\n	\n    {{ optionStrings|join(\' und \') }}\n{% endif %}\n\nDie Beschreibung sollte ca. 160 Zeichen lang sein.\nWichtig ist, dass die Ausgabe komplett in Deutsch erfolgt.\nSetzen Sie das Ergebnis nicht in Anführungszeichen.\n\nAls Grundlage für die Beschreibung dient folgender Beschreibungstext des Produktes:\n{{ product.translated.description }}',	'2024-10-09 14:38:51.561',	NULL),
                (UNHEX('019271B7F12A77979D011C575F465280'),	'product',	'metaDescription',	'dreiscSeoBulkProduct.defaultTemplates.metaDescription.openAiExampleEnglish',	0,	1,	'Create a search engine friendly SEO description for the product named: \n\'{{ product.translated.name }}\'\n{% if product.manufacturer.translated is defined %}\nfrom the manufacturer named: \'{{ product.manufacturer.translated.name }}\'\n{% endif %}\n\n{# Add the variant options, if it is a variant #}\n{% if isVariant and product.options is defined %}\n    The product is a variant with the following properties:\n    {% set optionStrings = [] %}\n	{% for option in product.options %}\n	    {% set singleOption = [option.group.translated.name, option.translated.name]|join(\'=\') %}\n	    {% set optionStrings = optionStrings|merge([singleOption]) %}\n	{% endfor %}\n	\n    {{ optionStrings|join(\' und \') }}\n{% endif %}\n\nThe description should be about 160 characters long.\nIt is important that the output is completely in English.\nDo not put the result in quotation marks.\n\nThe following description text of the product serves as the basis for the description:\n{{ product.translated.description }}',	'2024-10-09 14:40:38.373',	NULL),
                (UNHEX('019271BA396A7C81ABC96A814D534044'),	'product',	'url',	'dreiscSeoBulkProduct.defaultTemplates.url.openAiExampleGerman',	0,	1,	'Erstelle eine suchmaschinenfreundliche SEO-URL für das Produkt mit dem Namen:\n\'{{ product.translated.name }}\'\n{% if product.manufacturer.translated is defined %}\nvon dem Hersteller mit dem Namen: \'{{ product.manufacturer.translated.name }}\'\n{% endif %}\n\n{# Add the variant options, if it is a variant #}\n{% if isVariant and product.options is defined %}\n    Bei dem Produkt handelt es sich um eine Variante mit folgenden Eigenschaften:\n    {% set optionStrings = [] %}\n	{% for option in product.options %}\n	    {% set singleOption = [option.group.translated.name, option.translated.name]|join(\'=\') %}\n	    {% set optionStrings = optionStrings|merge([singleOption]) %}\n	{% endfor %}\n	\n    {{ optionStrings|join(\' und \') }}\n{% endif %}\n\nDie URL sollte maximal 75 Zeichen lang und in deutscher Sprache sein.\nDie Begriffe ‚seo url‘ und ‚Produkt‘ sollten in der Antwort nicht vorkommen.\n\nBeginne mit dem Herstellernamen, gefolgt von einem Schrägstrich. Verwende nur Kleinbuchstaben und ersetze Leerzeichen durch Bindestriche.\n\nAls Grundlage für die SEO-URL dient folgender Beschreibungstext des Produktes:\n{{ product.translated.description }}',	'2024-10-09 14:44:11.120',	'2024-10-10 06:33:08.855'),
                (UNHEX('019271C3346A705699866DF01F72991E'),	'product',	'url',	'dreiscSeoBulkProduct.defaultTemplates.url.openAiExampleEnglish',	0,	1,	'Create a search engine friendly SEO URL for the product named:\n\'{{ product.translated.name }}\'\n{% if product.manufacturer.translated is defined %}\nfrom the manufacturer named: \'{{ product.manufacturer.translated.name }}\'\n{% endif %}\n\n{# Add the variant options, if it is a variant #}\n{% if isVariant and product.options is defined %}\n    The product is a variant with the following properties:\n    {% set optionStrings = [] %}\n	{% for option in product.options %}\n	    {% set singleOption = [option.group.translated.name, option.translated.name]|join(\'=\') %}\n	    {% set optionStrings = optionStrings|merge([singleOption]) %}\n	{% endfor %}\n	\n    {{ optionStrings|join(\' und \') }}\n{% endif %}\n\nThe URL should be a maximum of 75 characters long and in English.\nThe terms \'seo url\' and \'product\' should not appear in the answer.\n\nStart with the manufacturer\'s name, followed by a slash. Use only lowercase letters and replace spaces with hyphens.\n\nThe following description text of the product serves as the basis for the SEO URL:\n{{ product.translated.description }}',	'2024-10-09 14:52:46.752',	NULL),
                (UNHEX('0192750B42A37B6BAF50D6ED20AA34EC'),	'category',	'metaTitle',	'dreiscSeoBulkCategory.defaultTemplates.metaTitle.openAiExampleGerman',	0,	1,	'Erstelle einen für Suchmaschinen geeigneten SEO-Titel für die Kategorieseite mit dem Namen: \n\'{{ category.translated.name }}\'\n\nDer Shopname sollte Teil des Titels sein. Dieser soll mit dem Wert \"##shopName##\" angegeben werden.\n\nDer Text sollte ca. 70 Zeichen lang sein.\nWichtig ist, dass die Ausgabe komplett in Deutsch erfolgt.\nSetzen Sie das Ergebnis nicht in Anführungszeichen.\n\nAls Grundlage für den SEO-Titel dient folgender Beschreibungstext der Kategorie:\n{{ category.translated.description }}',	'2024-10-10 06:10:24.096',	'2024-10-10 06:28:59.451'),
                (UNHEX('01927515996C7AA2A9744D3A8451D43C'),	'category',	'metaTitle',	'dreiscSeoBulkCategory.defaultTemplates.metaTitle.openAiExampleEnglish',	0,	1,	'Create a search engine friendly SEO title for the category page called:\n\'{{ category.translated.name }}\'\n\nThe shop name should be part of the title. This should be specified with the value \"##shopName##\".\n\nThe text should be about 70 characters long.\nIt is important that the output is completely in english.\nDo not put the result in quotation marks.\n\nThe following description text of the category serves as the basis for the SEO title:\n{{ category.translated.description }}',	'2024-10-10 06:21:01.831',	'2024-10-10 06:21:16.891'),
                (UNHEX('0192751DF0BA75329170B39B4F388121'),	'category',	'metaDescription',	'dreiscSeoBulkCategory.defaultTemplates.metaDescription.openAiExampleGerman',	0,	1,	'Erstelle eine für Suchmaschinen geeignete SEO-Beschreibung für die Kategorieseite mit dem Namen: \n\'{{ category.translated.name }}\'\n\nDer Shopname sollte Teil des Titels sein. Dieser soll mit dem Wert \"##shopName##\" angegeben werden.\n\nDer Text sollte ca. 160 Zeichen lang sein.\nWichtig ist, dass die Ausgabe komplett in Deutsch erfolgt.\nSetzen Sie das Ergebnis nicht in Anführungszeichen.\n\nAls Grundlage für den SEO-Titel dient folgender Beschreibungstext der Kategorie:\n{{ category.translated.description }}',	'2024-10-10 06:29:57.339',	NULL),
                (UNHEX('0192751F350373A2AC9736D20D0563BD'),	'category',	'metaDescription',	'dreiscSeoBulkCategory.defaultTemplates.metaDescription.openAiExampleEnglish',	0,	1,	'Create a search engine friendly SEO description for the category page with the name:\n\'{{ category.translated.name }}\'\n\nThe shop name should be part of the title. This should be specified with the value \"##shopName##\".\n\nThe text should be around 160 characters long.\nIt is important that the output is completely in english.\nDo not put the result in quotation marks.\n\nThe following description text of the category serves as the basis for the SEO title:\n{{ category.translated.description }}',	'2024-10-10 06:31:11.383',	'2024-10-10 06:31:21.332'),
                (UNHEX('01927520A43F782FB9B0B529BE3B8BEB'),	'category',	'url',	'dreiscSeoBulkCategory.defaultTemplates.url.openAiExampleGerman',	0,	1,	'Erstelle eine suchmaschinenfreundliche SEO-URL für die Shopkategorie mit dem Namen:\n\'{{ category.translated.name }}\'\nBeginne mit dem Name!\n\nDie URL sollte maximal 75 Zeichen lang sein.\nEs ist sehr wichtig, dass die Ausgabe komplett in deutscher Sprache ist.\nDie Begriffe ‚seo url‘ und ‚Produkt‘ sollten in der Antwort nicht vorkommen.\n\nVerwende nur Kleinbuchstaben und ersetze Leerzeichen durch Bindestriche.\n\nAls Grundlage für die SEO-URL dient folgender Beschreibungstext der Kategorie:\n{{ category.translated.description }}',	'2024-10-10 06:32:58.434',	'2024-10-10 06:39:00.081'),
                (UNHEX('019275246B9D768F876BA2AB8DD82214'),	'category',	'url',	'dreiscSeoBulkCategory.defaultTemplates.url.openAiExampleEnglish',	0,	1,	'Create a search engine friendly SEO URL for the shop category with the name:\n\'{{ category.translated.name }}\'\nStart with the name!\n\nThe URL should be a maximum of 75 characters long.\nIt is very important that the output is completely in English.\nThe terms \'seo url\' and \'product\' should not appear in the answer.\n\nUse only lowercase letters and replace spaces with hyphens.\n\nThe following description text of the category serves as the basis for the SEO URL:\n{{ category.translated.description }}',	'2024-10-10 06:36:52.703',	'2024-10-10 06:39:36.102');
            ");
        } catch (\Exception) { }
    }

    public function updateDestructive(Connection $connection): void
    {
        // implement update destructive
    }
}
