<?php declare(strict_types=1);

namespace DreiscSeoPro\Migration;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Migration\MigrationStep;

class Migration9000000005InsertSocialMediaDefaultBulkTemplates extends MigrationStep
{
    public function getCreationTimestamp(): int
    {
        return (int) 9_000_000_005;
    }

    public function update(Connection $connection): void
    {
        /** Try block to support the --keep-user-data uninstall */
        try {
            $connection->executeStatement("
                INSERT INTO `dreisc_seo_bulk_template` (`id`, `area`, `seo_option`, `name`, `spaceless`, `template`, `created_at`, `updated_at`) VALUES
                (UNHEX('4CA74745B77E482F931F65469DDF098B'),	'category',	'facebookDescription',	'dreiscSeoBulkCategory.defaultTemplates.facebookDescription.customFieldOrCategoryNameAsFallback',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if category.customFields.custom_myfield is defined %}\n    {{ category.customFields.custom_myfield }}\n{% else %}\n    {{ category.translated.name }}\n{% endif %}',	'2020-06-10 13:02:58.163',	NULL),
                (UNHEX('A27C5D6E8FF24DCE821B71CD91CD9B1F'),	'category',	'facebookDescription',	'dreiscSeoBulkCategory.defaultTemplates.facebookDescription.metaDescriptionOrCategoryName',	1,	'{% if category.metaDescription is not empty %}\n    {{ category.metaDescription }}\n{% else %}\n    {# Config of the maximal string length #}\n    {% set maxLength = 65 %}\n\n    {% if category.translated.description|length > maxLength %}\n        {# Trim the text if it is longer then the maximal string length  #}\n        {{ category.translated.description|slice(0, maxLength-3) ~ \'...\' }}\n    {% else %}\n        {# We take over the text, because the length is okay #}\n        {{ category.translated.description }}\n    {% endif %}\n{% endif %}',	'2020-06-10 13:03:59.021',	NULL),
                (UNHEX('89F489CE8414466DAA4623E1FE92701A'),	'category',	'facebookTitle',	'dreiscSeoBulkCategory.defaultTemplates.facebookTitle.customFieldOrCategoryNameAsFallback',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if category.customFields.custom_myfield is defined %}\n    {{ category.customFields.custom_myfield }}\n{% else %}\n    {{ category.translated.name }}\n{% endif %}',	'2020-06-10 13:00:37.958',	NULL),
                (UNHEX('D802C19F7B014374B0A1BF635CA26F6F'),	'category',	'facebookTitle',	'dreiscSeoBulkCategory.defaultTemplates.facebookTitle.metaTitleOrCategoryName',	1,	'{% if category.metaTitle is not empty %}\n    {{ category.metaTitle }}\n{% else %}\n    {{ category.translated.name }}\n{% endif %}',	'2020-06-10 13:01:22.547',	NULL),
                (UNHEX('47030C44819349D4A97704752E227DBD'),	'category',	'twitterDescription',	'dreiscSeoBulkCategory.defaultTemplates.twitterDescription.customFieldOrCategoryNameAsFallback',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if category.customFields.custom_myfield is defined %}\n    {{ category.customFields.custom_myfield }}\n{% else %}\n    {{ category.translated.name }}\n{% endif %}',	'2020-06-10 13:05:50.603',	NULL),
                (UNHEX('4A7D93CE4F0E4985B7F981BE638CD881'),	'category',	'twitterDescription',	'dreiscSeoBulkCategory.defaultTemplates.twitterDescription.metaDescriptionOrCategoryName',	1,	'{% if category.metaDescription is not empty %}\n    {{ category.metaDescription }}\n{% else %}\n    {# Config of the maximal string length #}\n    {% set maxLength = 110 %}\n\n    {% if category.translated.description|length > maxLength %}\n        {# Trim the text if it is longer then the maximal string length  #}\n        {{ category.translated.description|slice(0, maxLength-3) ~ \'...\' }}\n    {% else %}\n        {# We take over the text, because the length is okay #}\n        {{ category.translated.description }}\n    {% endif %}\n{% endif %}',	'2020-06-10 13:06:13.531',	NULL),
                (UNHEX('304379B0ADCD42A182967F5F3314FC76'),	'category',	'twitterTitle',	'dreiscSeoBulkCategory.defaultTemplates.twitterTitle.customFieldOrCategoryNameAsFallback',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if category.customFields.custom_myfield is defined %}\n    {{ category.customFields.custom_myfield }}\n{% else %}\n    {{ category.translated.name }}\n{% endif %}',	'2020-06-10 13:04:38.880',	NULL),
                (UNHEX('7BB7DDB1F15548E59391F1674AE7EDBE'),	'category',	'twitterTitle',	'dreiscSeoBulkCategory.defaultTemplates.twitterTitle.metaTitleOrCategoryName',	1,	'{% if category.metaTitle is not empty %}\n    {{ category.metaTitle }}\n{% else %}\n    {{ category.translated.name }}\n{% endif %}',	'2020-06-10 13:04:59.070',	NULL),
                (UNHEX('8B450C8D72A1406590CC3031BA18C9B0'),	'product',	'facebookDescription',	'dreiscSeoBulkProduct.defaultTemplates.facebookDescription.customFieldOrProductNameAsFallback',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if product.customFields.custom_myfield is defined %}\n    {{ product.customFields.custom_myfield }}\n{% else %}\n    {{ product.translated.name }}\n{% endif %}',	'2020-06-10 12:49:58.205',	NULL),
                (UNHEX('AE08BCA526334CF1BF39D37380108767'),	'product',	'facebookDescription',	'dreiscSeoBulkProduct.defaultTemplates.facebookDescription.metaDescriptionOrProductName',	1,	'{% if product.metaDescription is not empty %}\n    {{ product.metaDescription }}\n{% else %}\n    {# Config of the maximal string length #}\n    {% set maxLength = 65 %}\n\n    {% if product.translated.description|striptags|length > maxLength %}\n        {# Trim the text if it is longer then the maximal string length  #}\n        {{ product.translated.description|striptags|slice(0, maxLength-3) ~ \'...\' }}\n    {% else %}\n        {# We take over the text, because the length is okay #}\n        {{ product.translated.description|striptags }}\n    {% endif %}\n{% endif %}',	'2020-06-10 12:49:18.026',	'2020-06-10 12:51:55.648'),
                (UNHEX('2A67A732426C4191943FA799C518913D'),	'product',	'facebookTitle',	'dreiscSeoBulkProduct.defaultTemplates.facebookTitle.customFieldOrProductNameAsFallback',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if product.customFields.custom_myfield is defined %}\n    {{ product.customFields.custom_myfield }}\n{% else %}\n    {{ product.translated.name }}\n{% endif %}',	'2020-06-10 12:33:35.207',	'2020-06-10 12:33:43.774'),
                (UNHEX('E536EF0E698E4DB9884B94E0A1C239F8'),	'product',	'facebookTitle',	'dreiscSeoBulkProduct.defaultTemplates.facebookTitle.metaTitleOrProductName',	1,	'{% if product.metaTitle is not empty %}\n    {{ product.metaTitle }}\n{% else %}\n    {{ product.translated.name }}\n{% endif %}',	'2020-06-10 12:30:01.155',	NULL),
                (UNHEX('4B36A4BD06B4436093A64C1AAF40CA23'),	'product',	'twitterDescription',	'dreiscSeoBulkProduct.defaultTemplates.twitterDescription.customFieldOrProductNameAsFallback',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if product.customFields.custom_myfield is defined %}\n    {{ product.customFields.custom_myfield }}\n{% else %}\n    {{ product.translated.name }}\n{% endif %}',	'2020-06-10 12:50:33.852',	NULL),
                (UNHEX('B8B4F0A2653240729CD34C4D6DB1B671'),	'product',	'twitterDescription',	'dreiscSeoBulkProduct.defaultTemplates.twitterDescription.metaDescriptionOrProductName',	1,	'{% if product.metaDescription is not empty %}\n    {{ product.metaDescription }}\n{% else %}\n    {# Config of the maximal string length #}\n    {% set maxLength = 110 %}\n\n    {% if product.translated.description|striptags|striptags|length > maxLength %}\n        {# Trim the text if it is longer then the maximal string length  #}\n        {{ product.translated.description|striptags|slice(0, maxLength-3) ~ \'...\' }}\n    {% else %}\n        {# We take over the text, because the length is okay #}\n        {{ product.translated.description|striptags }}\n    {% endif %}\n{% endif %}',	'2020-06-10 12:50:54.511',	'2020-06-10 12:52:54.295'),
                (UNHEX('66F261AC9C8E4C94B883749FED3B4B88'),	'product',	'twitterTitle',	'dreiscSeoBulkProduct.defaultTemplates.twitterTitle.metaTitleOrProductName',	1,	'{% if product.metaTitle is not empty %}\n    {{ product.metaTitle }}\n{% else %}\n    {{ product.translated.name }}\n{% endif %}',	'2020-06-10 12:46:27.121',	NULL),
                (UNHEX('AE651F88C6664BF3810ECD360B3733BE'),	'product',	'twitterTitle',	'dreiscSeoBulkProduct.defaultTemplates.twitterTitle.customFieldOrProductNameAsFallback',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if product.customFields.custom_myfield is defined %}\n    {{ product.customFields.custom_myfield }}\n{% else %}\n    {{ product.translated.name }}\n{% endif %}',	'2020-06-10 12:37:05.615',	NULL);
            ");
        } catch (\Exception) { }
    }

    public function updateDestructive(Connection $connection): void
    {
        // implement update destructive
    }
}
