<?php declare(strict_types=1);

namespace DreiscSeoPro\Migration;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Migration\MigrationStep;

class Migration9000000001InsertDefaultBulkTemplates extends MigrationStep
{
    public function getCreationTimestamp(): int
    {
        return (int) 9_000_000_001;
    }

    public function update(Connection $connection): void
    {
        /** Try block to support the --keep-user-data uninstall */
        try {
            $connection->executeStatement("
                INSERT INTO `dreisc_seo_bulk_template` (`id`, `area`, `seo_option`, `name`, `spaceless`, `template`, `created_at`, `updated_at`) VALUES
                (UNHEX('046E0A0ED8B545F7B9FDCBBA095D5ED2'),	'product',	'metaDescription',	'dreiscSeoBulkProduct.defaultTemplates.metaDescription.productNameShippingFreePriceAndShopName',	1,	'{% set metaTitle = [] %}\n\n{# Add the name of the product to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([product.translated.name]) %}\n\n{# Add the shipping free text to the metaTitle array if the product is shipping free #}\n{% if true == product.shippingFree %}\n    {% if \'de-DE\' == language.locale.code %}\n        {% set metaTitle = metaTitle|merge([\'versandkostenfrei\']) %}\n    {% else %}\n        {% set metaTitle = metaTitle|merge([\'free shipping\']) %}\n    {% endif %}\n{% endif %}\n\n{# Add the **for only** part to the metaTitle array #}\n{% if \'de-DE\' == language.locale.code %}\n    {% set metaTitle = metaTitle|merge([\'für nur\']) %}\n{% else %}\n    {% set metaTitle = metaTitle|merge([\'for only\']) %}\n{% endif %}\n\n{# Add the price live template variable to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([\'##productPrice##\']) %}\n\n{# Add the shop name live template variable to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([\'von ##shopName##\']) %}\n\n{# Convert the array to an string. Seperated by whitespaces #}\n{{ metaTitle|join(\' \') }}',	'2020-01-14 11:35:06.336',	NULL),
                (UNHEX('0A4CFD2133114560ADED711EEC64B29C'),	'product',	'metaDescription',	'dreiscSeoBulkProduct.defaultTemplates.metaDescription.trimmedProductDescription',	1,	'{# Config of the maximal string length #}\r\n{% set maxLength = 130 %}\r\n\r\n{% if product.translated.description|striptags|length > maxLength %}\r\n    {# Trim the text if it is longer then the maximal string length  #}\r\n    {{ product.translated.description|striptags|slice(0, maxLength-3) ~ \'...\' }}\r\n{% else %}\r\n    {# We take over the text, because the length is okay #}\r\n    {{ product.translated.description|striptags }}\r\n{% endif %}',	'2020-01-09 15:34:51.208',	'2020-01-09 15:36:28.435'),
                (UNHEX('0C15C748E069436C8D3E633ED6C76075'),	'category',	'metaDescription',	'dreiscSeoBulkCategory.defaultTemplates.metaDescription.trimmedCategoryDescription',	1,	'{# Config of the maximal string length #}\n{% set maxLength = 130 %}\n\n{% if category.translated.description|length > maxLength %}\n    {# Trim the text if it is longer then the maximal string length  #}\n    {{ category.translated.description|slice(0, maxLength-3) ~ \'...\' }}\n{% else %}\n    {# We take over the text, because the length is okay #}\n    {{ category.translated.description }}\n{% endif %}',	'2020-01-08 13:35:14.000',	'2020-01-09 15:33:33.255'),
                (UNHEX('10C8301253654347B80A66FDEE05A664'),	'category',	'url',	'dreiscSeoBulkCategory.defaultTemplates.url.categoryName',	1,	'{{ category.translated.name }}',	'2020-01-08 13:35:14.000',	'2020-01-08 13:35:14.000'),
                (UNHEX('139211D96C0F4B9F88C864591DC2F78A'),	'category',	'metaDescription',	'dreiscSeoBulkCategory.defaultTemplates.metaDescription.categoryNameAndShopName',	1,	'{{ category.translated.name }} | ##shopName##',	'2020-01-20 11:28:46.161',	NULL),
                (UNHEX('1745748E35774FAB80E4A065187A167D'),	'product',	'url',	'dreiscSeoBulkProduct.defaultTemplates.url.parentCategoryUrlAndProductName',	1,	'{% set url = [] %}\n\n{% if mainCategorySeo is defined and null != mainCategorySeo.url %}\n    {# Make sure that there is no slash at the end of the main category url #}\n    {% set mainCategoryUrl = mainCategorySeo.url|rtrim(\'/\') %}\n    {# Add the main url without ending slash to the url array #}\n    {% set url = url|merge([mainCategoryUrl]) %}\n{% endif %}\n\n{# Add the name of the product to the url array #}\n{% set url = url|merge([product.translated.name]) %}\n\n{# Add the product number, if it is a variant #}\n{% if isVariant %}\n    {% set url = url|merge([product.productNumber]) %}\n{% endif %}\n\n{# Convert the array to an string and output. Seperated by slashes #}\n{{ url|join(\'/\') }}',	'2020-01-09 09:39:02.860',	'2020-01-22 13:33:30.704'),
                (UNHEX('18AA4E3B2D964DC581111154B814DB93'),	'category',	'metaTitle',	'dreiscSeoBulkCategory.defaultTemplates.metaTitle.categoryNameAndShippingFreeText',	1,	'{% set metaTitle = [] %}\n\n{# Add the name of the category to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([category.translated.name]) %}\n\n{# Add the shipping free text to the array #}\n{% if \'de-DE\' == language.locale.code %}\n    {% set metaTitle = metaTitle|merge([\'versandkostenfrei einkaufen\']) %}\n{% else %}\n    {% set metaTitle = metaTitle|merge([\'free shipping\']) %}\n{% endif %}\n\n{# Convert the array to an string. Seperated by whitespaces #}\n{{ metaTitle|join(\' \') }}',	'2020-01-08 13:35:14.000',	'2020-01-20 11:29:40.559'),
                (UNHEX('19285658A69246C6B32206EC42D59F41'),	'product',	'metaDescription',	'dreiscSeoBulkProduct.defaultTemplates.metaDescription.productNameAndShopName',	1,	'{{ product.translated.name }} | ##shopName##',	'2020-01-14 11:34:34.652',	NULL),
                (UNHEX('2C1F5673F16740BEB0425C860AF6C4F8'),	'category',	'metaTitle',	'dreiscSeoBulkCategory.defaultTemplates.metaTitle.starsCategoryNameAndCustomText',	1,	'{% set metaTitle = [] %}\n\n{# Add the stars to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([\'⭐⭐⭐⭐⭐\']) %}\n\n{# Add the name of the category to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([category.translated.name]) %}\n\n{# Add the additional text to the array #}\n{% if \'de-DE\' == language.locale.code %}\n    {% set metaTitle = metaTitle|merge([\'» Top-Marken ✓ große Auswahl ✓\']) %}\n{% else %}\n    {% set metaTitle = metaTitle|merge([\'» Top brands ✓ large choice ✓\']) %}\n{% endif %}\n\n{# Convert the array to an string. Seperated by whitespaces #}\n{{ metaTitle|join(\' \') }}',	'2020-01-14 12:09:25.188',	'2020-01-14 12:14:51.892'),
                (UNHEX('4311C36AFB8742E196BF5473E8F8CD2D'),	'product',	'url',	'dreiscSeoBulkProduct.defaultTemplates.url.productName',	1,	'{% set url = [] %}\n\n{# Add the product name #}\n{% set url = url|merge([product.translated.name]) %}\n\n{# Add the product number, if it is a variant #}\n{% if isVariant %}\n    {% set url = url|merge([product.productNumber]) %}\n{% endif %}\n\n{# Convert the array to an string and output. Seperated by slashes #}\n{{ url|join(\'/\') }}',	'2020-01-08 12:56:08.736',	'2020-01-22 13:32:57.947'),
                (UNHEX('45A1B109B46345879CD842CF43347EAC'),	'product',	'metaTitle',	'dreiscSeoBulkProduct.defaultTemplates.metaTitle.productNameManufacturePriceAndShopName',	1,	'{% set metaTitle = [] %}\n\n{# Add the name of the product to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([product.translated.name]) %}\n\n{# Add the manufacture to the metaTitle array #}\n{% if product.manufacturer.translated is defined %}\n    {% if \'de-DE\' == language.locale.code %}\n        {% set metaTitle = metaTitle|merge([\'von\', product.manufacturer.translated.name]) %}\n    {% else %}\n        {% set metaTitle = metaTitle|merge([\'(\' ~ product.manufacturer.translated.name ~ \')\']) %}\n    {% endif %}\n{% endif %}\n\n{# Add the **for only** part to the metaTitle array #}\n{% if \'de-DE\' == language.locale.code %}\n    {% set metaTitle = metaTitle|merge([\'für nur\']) %}\n{% else %}\n    {% set metaTitle = metaTitle|merge([\'for only\']) %}\n{% endif %}\n\n{# Add the price live template variable to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([\'##productPrice##\']) %}\n\n{# Add the shop name live template variable to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([\'von ##shopName##\']) %}\n\n{# Convert the array to an string. Seperated by whitespaces #}\n{{ metaTitle|join(\' \') }}',	'2020-01-14 11:04:42.609',	'2024-09-03 06:45:12.714'),
                (UNHEX('46736ED0F1C44167A79444B548924FAB'),	'category',	'url',	'dreiscSeoBulkCategory.defaultTemplates.url.customFieldIfExistOtherwiseCategoryName',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if category.customFields.custom_myfield is defined %}\n    {{ category.customFields.custom_myfield }}\n{% else %}\n    {{ category.translated.name }}\n{% endif %}',	'2020-01-15 16:52:45.544',	'2020-01-20 11:15:47.576'),
                (UNHEX('4CCF4414FCAB43699DB4914EB3364ABB'),	'product',	'metaTitle',	'dreiscSeoBulkProduct.defaultTemplates.metaTitle.productNameShippingFreePriceAndShopName',	1,	'{% set metaTitle = [] %}\n\n{# Add the name of the product to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([product.translated.name]) %}\n\n{# Add the shipping free text to the metaTitle array if the product is shipping free #}\n{% if true == product.shippingFree %}\n    {% if \'de-DE\' == language.locale.code %}\n        {% set metaTitle = metaTitle|merge([\'versandkostenfrei\']) %}\n    {% else %}\n        {% set metaTitle = metaTitle|merge([\'free shipping\']) %}\n    {% endif %}\n{% endif %}\n\n{# Add the **for only** part to the metaTitle array #}\n{% if \'de-DE\' == language.locale.code %}\n    {% set metaTitle = metaTitle|merge([\'für nur\']) %}\n{% else %}\n    {% set metaTitle = metaTitle|merge([\'for only\']) %}\n{% endif %}\n\n{# Add the price live template variable to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([\'##productPrice##\']) %}\n\n{# Add the shop name live template variable to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([\'von ##shopName##\']) %}\n\n{# Convert the array to an string. Seperated by whitespaces #}\n{{ metaTitle|join(\' \') }}',	'2020-01-10 13:52:42.196',	'2020-01-10 14:19:03.963'),
                (UNHEX('5520811467274810BC2AEF0165D5D116'),	'product',	'metaTitle',	'dreiscSeoBulkProduct.defaultTemplates.metaTitle.productName',	1,	'{{ product.translated.name }}',	'2020-01-08 13:35:14.000',	'2020-01-08 13:35:14.000'),
                (UNHEX('56E12B4AAF854A39B9ED09C08AD94C8F'),	'product',	'url',	'dreiscSeoBulkProduct.defaultTemplates.url.metaTitleOrProductNameAsFallback',	1,	'{% set url = [] %}\n\n{% if productSeo.metaTitle %}\n    {# Use the meta title of the product, if defined #}\n    {% set url = url|merge([productSeo.metaTitle]) %}\n{% else %}\n    {# Otherwise use the name of the product #}\n    {% set url = url|merge([product.translated.name]) %}\n{% endif %}\n\n{# Add the product number, if it is a variant #}\n{% if isVariant %}\n    {% set url = url|merge([product.productNumber]) %}\n{% endif %}\n\n{# Convert the array to an string and output. Seperated by slashes #}\n{{ url|join(\'/\') }}',	'2020-01-08 12:51:46.504',	'2020-01-22 13:29:58.957'),
                (UNHEX('590E419AF32440778FFF868380B7ABDF'),	'product',	'url',	'dreiscSeoBulkProduct.defaultTemplates.url.manufacturerAndProductName',	1,	'{% set url = [] %}\n\n{# Add the manufacturer name #}\n{% if product.manufacturer.translated is defined %}\n    {% if product.manufacturer is defined %}\n        {% set url = url|merge([product.manufacturer.translated.name]) %}\n    {% endif %}\n{% endif %}\n\n{# Add the product name #}\n{% set url = url|merge([product.translated.name]) %}\n\n{# Add the product number, if it is a variant #}\n{% if isVariant %}\n    {% set url = url|merge([product.productNumber]) %}\n{% endif %}\n\n{# Convert the array to an string and output. Seperated by slashes #}\n{{ url|join(\'/\') }}',	'2020-01-08 16:45:31.341',	'2024-09-03 06:47:01.692'),
                (UNHEX('682A11EBF4CE474BA3E33EBBEB877ACD'),	'category',	'metaDescription',	'dreiscSeoBulkCategory.defaultTemplates.metaDescription.customFieldIfExistOtherwiseCategoryName',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if category.customFields.custom_myfield is defined %}\n    {{ category.customFields.custom_myfield }}\n{% else %}\n    {{ category.translated.name }}\n{% endif %}',	'2020-01-20 11:30:03.700',	NULL),
                (UNHEX('6DB1527EF09F451EB4ADA9B6F84C0AE4'),	'category',	'metaTitle',	'dreiscSeoBulkCategory.defaultTemplates.metaTitle.categoryName',	1,	'{{ category.translated.name }}',	'2020-01-08 13:35:14.000',	'2020-01-08 13:35:14.000'),
                (UNHEX('7B735A0E8C18420E955DD560F4DE37F6'),	'product',	'metaDescription',	'dreiscSeoBulkProduct.defaultTemplates.metaDescription.customFieldOrProductNameAsFallback',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if product.customFields.custom_myfield is defined %}\n    {{ product.customFields.custom_myfield }}\n{% else %}\n    {{ product.translated.name }}\n{% endif %}',	'2020-01-08 16:23:38.121',	'2020-01-09 16:19:27.999'),
                (UNHEX('85D5E83A528447139C1F48F10F1DBF1A'),	'product',	'url',	'dreiscSeoBulkProduct.defaultTemplates.url.introTextAndProductName',	1,	'{% set url = [] %}\n\n{# Add the custom text part #}\n{% if \'de-DE\' == language.locale.code %}\n    {% set url = url|merge([\'unsere-topseller\']) %}\n{% else %}\n    {% set url = url|merge([\'our-topseller\']) %}\n{% endif %}\n\n{# Add the product name #}\n{% set url = url|merge([product.translated.name]) %}\n\n{# Add the product number, if it is a variant #}\n{% if isVariant %}\n    {% set url = url|merge([product.productNumber]) %}\n{% endif %}\n\n{# Convert the array to an string and output. Seperated by slashes #}\n{{ url|join(\'/\') }}',	'2020-01-09 14:25:12.808',	'2020-01-22 13:27:11.827'),
                (UNHEX('8F4A179873344D6C81B9B81325B25ECC'),	'product',	'url',	'dreiscSeoBulkProduct.defaultTemplates.url.customFieldOrProductNameAsFallback',	1,	'{% set url = [] %}\n\n{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if product.customFields.custom_myfield is defined %}\n    {% set url = url|merge([product.customFields.custom_myfield]) %}\n{% else %}\n    {% set url = url|merge([product.translated.name]) %}\n{% endif %}\n\n{# Add the product number, if it is a variant #}\n{% if isVariant %}\n    {% set url = url|merge([product.productNumber]) %}\n{% endif %}\n\n{# Convert the array to an string and output. Seperated by slashes #}\n{{ url|join(\'/\') }}',	'2020-01-08 16:34:39.666',	'2020-01-22 13:28:51.686'),
                (UNHEX('9A3A7BB978BC442A8BCF252FFA2B7D2A'),	'category',	'metaDescription',	'dreiscSeoBulkCategory.defaultTemplates.metaDescription.introTextAndChildCategoryNames',	1,	'{# Fetches the names of all child categories #}\n{% set childCategoryNames = [] %}\n\n{% for childCategory in childCategories %}\n    {% set childCategoryNames = childCategoryNames|merge([childCategory.translated.name]) %}\n{% endfor %}\n\n{# Output, if child categories available #}\n{% if childCategoryNames|length > 0 %}\n    {# Define the custom text #}\n    {% if \'de-DE\' == language.locale.code %}\n        {% set customText = \'Alles aus einer Hand\' %}\n    {% else %}\n        {% set customText = \'All from a single source\' %}\n    {% endif %}\n\n    {{ customText }}: {{ childCategoryNames|join(\', \') }}\n{% else %}\n    {# Since there are no child categories, the category name is output #}\n    {{ category.translated.name }}\n{% endif %}',	'2020-01-08 13:35:14.000',	'2020-01-20 11:42:15.490'),
                (UNHEX('AA1F3945694D4F8586DDFEE0509D2ADE'),	'product',	'url',	'dreiscSeoBulkProduct.defaultTemplates.url.productNameAndVariantOptions',	1,	'{% set url = [] %}\n{% set seperatorBetweenGroupAndOption = \'-\' %}\n{% set seperatorBetweenOptions = \'/\' %}\n\n{# Add the product name #}\n{% set url = url|merge([product.translated.name]) %}\n\n{# Add the variant options, if it is a variant #}\n{% if isVariant %}\n    {% if product.options is defined %}\n        {% set optionStrings = [] %}\n    	{% for option in product.options %}\n    	    {% set singleOption = [option.group.translated.name, option.translated.name]|join(seperatorBetweenGroupAndOption) %}\n    	    {% set optionStrings = optionStrings|merge([singleOption]) %}\n    	{% endfor %}\n    	\n    	{% set optionStringsUrl = optionStrings|join(seperatorBetweenOptions) %}\n    	{% set url = url|merge([optionStringsUrl]) %}\n    {% endif %}\n{% endif %}\n\n{# Convert the array to an string and output. Seperated by slashes #}\n{{ url|join(\'/\') }}',	'2020-01-22 14:15:22.452',	'2020-01-22 14:26:27.876'),
                (UNHEX('AC20871476DD441CA00CE7D1A5C35FA2'),	'category',	'url',	'dreiscSeoBulkCategory.defaultTemplates.url.metaTitleIfAvailableOrCategoryName',	1,	'{% if categorySeo.metaTitle %}\n    {# Use the meta title of the category, if defined #}\n    {{ categorySeo.metaTitle}}\n{% else %}\n    {# Otherwise use the name of the category #}\n    {{ category.translated.name }}\n{% endif %}',	'2020-01-15 16:52:35.819',	'2020-01-17 12:36:32.646'),
                (UNHEX('AD60969075FC4B8B9639D29C4758A48A'),	'category',	'url',	'dreiscSeoBulkCategory.defaultTemplates.url.parentCategoryUrlAndCategoryName',	1,	'{% set url = [] %}\n\n{% if categoryParentSeo is defined and null != categoryParentSeo.url %}\n    {# Make sure that there is no slash at the end of the parent category url #}\n    {% set categoryParentUrl = categoryParentSeo.url|rtrim(\'/\') %}\n    {# Add the url of the parent category without ending slash to the url array #}\n    {% set url = url|merge([categoryParentUrl]) %}\n{% endif %}\n\n{# Add the name of the category to the url array #}\n{% set url = url|merge([category.translated.name]) %}\n\n{# Convert the array to an string. Seperated by slashes #}\n{{ url|join(\'/\') }}',	'2020-01-15 16:52:24.021',	'2020-01-17 11:11:59.169'),
                (UNHEX('ADA65FADF316487097FE8BD4BABC3CB6'),	'category',	'metaTitle',	'dreiscSeoBulkCategory.defaultTemplates.metaTitle.customFieldIfExistOtherwiseCategoryName',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if category.customFields.custom_myfield is defined %}\n    {{ category.customFields.custom_myfield }}\n{% else %}\n    {{ category.translated.name }}\n{% endif %}',	'2020-01-14 12:15:47.768',	'2020-01-14 12:16:30.536'),
                (UNHEX('B8CE12B88DC24640AAB3279A3FCAF2B3'),	'category',	'metaTitle',	'dreiscSeoBulkCategory.defaultTemplates.metaTitle.categoryNameAndShopName',	1,	'{{ category.translated.name }} | ##shopName##',	'2020-01-14 11:49:49.600',	'2020-01-14 12:08:15.460'),
                (UNHEX('BB0F4736F3074E69A522AA83A008F9F7'),	'product',	'metaTitle',	'dreiscSeoBulkProduct.defaultTemplates.metaTitle.customFieldOrProductNameAsFallback',	1,	'{# HINWEIS: Ersetzen Sie **custom_myfield** durch den technischen Namen Ihres Zusatzfeldes #}\n{# NOTE: Replace **custom_myfield** with the technical name of your free text field #}\n{% if product.customFields.custom_myfield is defined %}\n    {{ product.customFields.custom_myfield }}\n{% else %}\n    {{ product.translated.name }}\n{% endif %}',	'2020-01-08 15:11:21.059',	'2020-01-08 15:13:46.919'),
                (UNHEX('C4B2B9B8854249DEA234863579307831'),	'product',	'metaDescription',	'dreiscSeoBulkProduct.defaultTemplates.metaDescription.productNameMAndProperties',	1,	'{% set metaTitle = [] %}\n\n{# Add the name of the product to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([product.translated.name]) %}\n\n{# Add the product properties #}\n{% set groupNames = [] %}\n{% set propertiesGroupedByProperties = [] %}\n{% if product.properties is defined %}\n	{% for property in product.properties %}\n	    {% set groupId = property.groupId %} \n	    {% set groupName = property.group.translated.name %} \n	    {% set propertyName = property.translated.name %}\n	    \n	    {# Store the group name #}\n	    {% if groupNames[groupId] is not defined %}\n	        {% set groupNames = groupNames|merge({\n            (groupId): groupName\n        }) %}\n	    {% endif %}\n	    \n	    {# Recalculate the properties array #}\n	    {% if propertiesGroupedByProperties[groupId] is not defined %}\n	        {% set properties = [ propertyName ] %}\n        {% else %}\n	        {% set properties = propertiesGroupedByProperties[groupId]|merge([propertyName]) %}\n	    {% endif %}\n	    \n	    {# Refesh the propertiesGroupedByProperties array #}\n	    {% set propertiesGroupedByProperties = propertiesGroupedByProperties|merge({\n            (groupId): properties\n        }) %}\n	    \n    {% endfor %}\n{% endif %}\n\n{# Output the properties #}\n{% set propertyStrings = [] %}\n{% for groupKey, groupName in groupNames %}\n    {% set concatedProperties = propertiesGroupedByProperties[groupKey]|join(\', \') %}\n    {% set propertyStrings = propertyStrings|merge([ groupName ~ \': \' ~ concatedProperties ]) %}\n{% endfor %}\n\n{# Add the property string to the metaTitle array #}\n{% if propertyStrings|count() > 0 %}\n    {% set propertySingleString = propertyStrings|join(\'; \') %}\n    {% set metaTitle = metaTitle|merge([\'(\' ~ propertySingleString ~ \')\']) %}\n{% endif %}\n\n\n{# Convert the array to an string. Seperated by whitespaces #}\n{{ metaTitle|join(\' \') }}\n',	'2020-01-20 16:48:51.181',	'2020-01-20 17:00:17.203'),
                (UNHEX('D8835A4D93554C9390F3F5FF470AD5ED'),	'category',	'metaDescription',	'dreiscSeoBulkCategory.defaultTemplates.metaDescription.categoryNameAndShippingFreeText',	1,	'{% set metaTitle = [] %}\n\n{# Add the name of the category to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([category.translated.name]) %}\n\n{# Add the shipping free text to the array #}\n{% if \'de-DE\' == language.locale.code %}\n    {% set metaTitle = metaTitle|merge([\'versandkostenfrei einkaufen\']) %}\n{% else %}\n    {% set metaTitle = metaTitle|merge([\'free shipping\']) %}\n{% endif %}\n\n{# Convert the array to an string. Seperated by whitespaces #}\n{{ metaTitle|join(\' \') }}',	'2020-01-20 11:29:31.913',	NULL),
                (UNHEX('D98D63A7C8714AB09FC61ABF51CE48BB'),	'product',	'metaDescription',	'dreiscSeoBulkProduct.defaultTemplates.metaDescription.productNameManufacturePriceAndShopName',	1,	'{% set metaTitle = [] %}\n\n{# Add the name of the product to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([product.translated.name]) %}\n\n{# Add the manufacture to the metaTitle array #}\n{% if product.manufacturer.translated is defined %}\n    {% if \'de-DE\' == language.locale.code %}\n        {% set metaTitle = metaTitle|merge([\'von\', product.manufacturer.translated.name]) %}\n    {% else %}\n        {% set metaTitle = metaTitle|merge([\'(\' ~ product.manufacturer.translated.name ~ \')\']) %}\n    {% endif %}\n{% endif %}\n\n{# Add the **for only** part to the metaTitle array #}\n{% if \'de-DE\' == language.locale.code %}\n    {% set metaTitle = metaTitle|merge([\'für nur\']) %}\n{% else %}\n    {% set metaTitle = metaTitle|merge([\'for only\']) %}\n{% endif %}\n\n{# Add the price live template variable to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([\'##productPrice##\']) %}\n\n{# Add the shop name live template variable to the metaTitle array #}\n{% set metaTitle = metaTitle|merge([\'von ##shopName##\']) %}\n\n{# Convert the array to an string. Seperated by whitespaces #}\n{{ metaTitle|join(\' \') }}',	'2020-01-14 11:35:33.870',	'2024-09-03 06:46:16.527'),
                (UNHEX('E0EDC4396BA1455590705FEDC5FC80EC'),	'product',	'metaTitle',	'dreiscSeoBulkProduct.defaultTemplates.metaTitle.productNameAndShopName',	1,	'{{ product.translated.name }} | ##shopName##',	'2020-01-09 16:54:30.860',	'2020-01-09 16:57:45.339'),
                (UNHEX('FD01EEBFD43E438EBD26CF1F8895DB48'),	'product',	'metaTitle',	'dreiscSeoBulkProduct.defaultTemplates.metaTitle.productNameAndVariantOptions',	1,	'{% set metaTitle = [] %}\n{% set seperatorBetweenProductNameAndOptions = \' » \' %}\n{% set seperatorBetweenGroupAndOption = \': \' %}\n{% set seperatorBetweenOptions = \', \' %}\n\n{# Add the product name #}\n{% set metaTitle = metaTitle|merge([product.translated.name]) %}\n\n{# Add the variant options, if it is a variant #}\n{% if isVariant %}\n    {% if product.options is defined %}\n        {% set metaTitle = metaTitle|merge([seperatorBetweenProductNameAndOptions]) %}\n    \n        {% set optionStrings = [] %}\n    	{% for option in product.options %}\n    	    {% set singleOption = [option.group.translated.name, option.translated.name]|join(seperatorBetweenGroupAndOption) %}\n    	    {% set optionStrings = optionStrings|merge([singleOption]) %}\n    	{% endfor %}\n    	\n    	{% set optionStringsUrl = optionStrings|join(seperatorBetweenOptions) %}\n    	{% set metaTitle = metaTitle|merge([optionStringsUrl]) %}\n    {% endif %}\n{% endif %}\n\n{# Convert the array to an string and output. Seperated by whitespace #}\n{{ metaTitle|join(\' \') }}',	'2020-01-22 14:31:57.706',	'2020-01-22 14:33:13.341');
            ");
        } catch (\Exception) { }
    }

    public function updateDestructive(Connection $connection): void
    {
        // implement update destructive
    }
}
